version: '3.8'

services:
  dashboard:
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - PYTHONAPP=/app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/dashboard/config:/app/src/dashboard/config
      - ./src/dashboard/schemas:/app/src/dashboard/schemas
      - ./src/dashboard/assets:/app/src/dashboard/assets
      - ./src/dashboard/db:/app/src/dashboard/db
    restart: unless-stopped
